[build]
  # مجلد البناء
  publish = "dist"
  
  # أمر البناء
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  # متغيرات البيئة للبناء
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# إعدادات إعادة التوجيه للـ SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# إعدادات الرؤوس
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co https://*.netlify.app;"

# إعدادات الأمان
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# إعدادات الترجمة
[context.production.environment]
  VITE_APP_ENV = "production"

[context.deploy-preview.environment]
  VITE_APP_ENV = "preview"

[context.branch-deploy.environment]
  VITE_APP_ENV = "development"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
  framework = "#custom" 